### ISSUE TITLE
Cannot create postgres instance with max_connections configuration

### ISSUE THREAD

**Issue by mrennie** [terraform-ibm-modules/terraform-ibm-icd-postgresql#273] opened 2023-09-12 19:04 UTC
### Affected modules

This module and any other modules that consume it

### Terraform CLI and Terraform provider versions

Terraform v1.5.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/ibm-cloud/ibm v1.56.2

### Terraform output

```
Error: 1 error occurred:
│ 	* [ERROR] configuration contained invalid field(s): [max_replication_slots max_wal_senders shared_buffers archive_timeout effective_io_concurrency log_min_duration_statement deadlock_timeout max_prepared_transactions synchronous_commit wal_level]
│ 
│ 
│ 
│   with module.gitlab-icdpostgres15-eu-es.ibm_database.postgresql_db,
│   on .terraform/modules/gitlab-icdpostgres15-eu-es/main.tf line 50, in resource "ibm_database" "postgresql_db":
│   50: resource "ibm_database" "postgresql_db" {
```

### Expected behavior

I would expect to be able to create a new postgres instance with 500  max connections

### Actual behavior

Failed with the error listed

### Steps to reproduce (including links and screen captures)

Run `terraform plan` with the following postgres module use (provide the ID of an existing resource group):
```
module "gitlab-icdpostgres15-eu-es" {
  source                        = "terraform-ibm-modules/icd-postgresql/ibm"
  resource_group_id             = {fill in with existing resource group ID}
  name                          = "gitlab-icdpostgres15-eu-es"
  pg_version                    = 14
  service_endpoints             = "public-and-private"
  skip_iam_authorization_policy = false
  configuration = {
    max_connections = 500
  }

  # Resources
  members          = 2
  member_cpu_count = 4
  member_disk_mb   = 131072
  member_memory_mb = 65536
}
```

### Anything else

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment] 2023-09-22 15:06
PR: https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/pull/284

**Comment by akocbek** [comment] 2023-09-22 16:05
the problem is the following:
`var.configuration` input variable has optional attributes. In a case that at least one optional attribute of configuration is set, then others are automatically set to `null`. `jsonencode` call doesn't remove `null` values. if `null` value is send to ibm provider then an error is thrown. To prevent this we need to remove `null` values from configuration input variable. 

solution is to use `jsonencode({ for k, v in var.configuration : k => v if v != null })`

**Comment by akocbek** [comment] 2023-09-26 13:36
@mrennie Fix has been merged, please try again.

**Closed** 2023-09-26 13:37 UTC
